Правда или действие (часть 1)
htmlacademy-javascript/1797575-keksobooking-24 pull request #7
Opened 2021-11-10 12:05 UTC by NinaS7

2021-11-11 06:29 UTC, 4err requested changes
Внезапно что-то не так с активацией. Страница не активирована и проверить работу валидации невозможно.

2021-11-12 00:11 UTC, NinaS7 commented
Окно активно, но какая-то беда с ценой((((  Валидация срабатывает через раз! И, даже при валидном значении, при отправке формы указывает на ошибку заполнения в этом поле. Не могу понять, что не так(

2021-11-12 00:16 UTC, NinaS7 commented
> Внезапно что-то не так с активацией. Страница не активирована и проверить работу валидации невозможно.

Окно активно, но какая-то беда с ценой(((( Валидация срабатывает через раз! И, даже при валидном значении, при отправке формы указывает на ошибку заполнения в этом поле. Не могу понять, что не так(

2021-11-12 05:37 UTC, 4err requested changes
На price input нет события. Соответственно когда мы выбрали какой-то тип жилья, а затем ввели что-то в поле цены, наша валидация не перепроверилась. Нужно проверять соответствие жилья и при смене селектора и при вводе цены.

2021-11-12 05:37 UTC, 4err commented on js/form.js
> +  } else
На самом деле тут `else` не нужен. это две независимые проверки, они никак одновременно сработать не смогут.

2021-11-12 05:37 UTC, 4err commented on js/form.js
> +  };
Функцию стоит вынести из обработчика.

2021-11-12 09:22 UTC, 4err requested changes

2021-11-12 09:22 UTC, 4err commented on js/form.js
> +type.addEventListener('change', getMinPrice);
А зачем два события то? Просто запускай функцию внутри второго обработчика и все. Нужно было вынести только объявление функции

2021-11-12 12:55 UTC, merged